### ISSUE TITLE
## Pre-trained model

### ISSUE THREAD

**Issue by zhanglei-underdog** [hee9joon/ViT-VisionTransformer#1]
May I ask the author, can this project load Google's pre-trained model on imagenet?

**Comment by hee9joon** [comment]
Thank you for your interest to my repo. Unfortunately it cannot load the Google's pre-trained model on ImageNet.

**Comment by zhanglei-underdog** [comment]
> Thank you for your interest to my repo. Unfortunately it cannot load the Google's pre-trained model on ImageNet.

All right, thank you very much for your reply ~
